### ISSUE TITLE
Use inode / dentry hash in sb_mount LSM hook

### ISSUE THREAD

**Issue by vadorovsky** [rancher-sandbox/lockc#114]
Currently in our `sb_mount` LSM hook program we do expensive string matching:

https://github.com/rancher-sandbox/lockc/blob/main/lockc/src/bpf/lockc.bpf.c#L236-L281

That's because the `sb_mount` LSM hook provides the mount source of bind mounts as a string, not as an inode/path/dentry. See:

```c
LSM_HOOK(int, 0, sb_mount, const char *dev_name, const struct path *path,
	 const char *type, unsigned long flags, void *data)
```

Fpr bind mounts, the source mount is provided as `const char *dev_name`. Don't be confused by `*path` argument - it's a destination.

Because of that, our BPF maps related to mounting have strings as map keys. That's not a good solution in terms of performance.

A good solution would be getting the inode/dentry somehow before `sb_mount`. And then use inode ID or dentry hash as map keys and use it in sb_mount.

**Comment by willfindlay** [comment]
Some additional context: This would probably involve hunting for a function that includes the superblock struct for the mount source somewhere along the mount(2) codepath. Then storing intermediary state in a percpu map and looking it up inside the sb_mount hook program. The first step is finding such a function (if one exists).

**Comment by vadorovsky** [comment]
We discussed this issue in details yesterday and we have a solid plan how to proceed :muscle: 

https://hackmd.io/@lockc/SJAv8SC5t

**Comment by vadorovsky** [comment]
I tried to implement that, but the PATH_TO_INODE map was getting too large. I will keep this issue closed and open an another one for the other option - using LPM_TRIE map for string matching - #134

If we ever feel like we should tink about this solution again, let's repoen.

**Comment by vadorovsky** [comment]
Opened also #141
