### ISSUE TITLE
Updating lockc with custom lockc.toml causes problems

### ISSUE THREAD

**Issue by mjura** [rancher-sandbox/lockc#130]
After deploying lockc.toml from ConfigMap causes issues with starting pods in restricted namespace.

How to reproduce it:
1. Add changes to lockc.toml and create configMap in lockc namespace
2. Create it 
```
kubectl create configmap -n lockc lockc --from-file=./lockc.toml
```
3. Upgrade already existing lockc helm release
```
helm upgrade -n lockc lockc lockc --set lockcd.config.enabled=true --set lockcd.image.repository=ttl.sh/lockcd --set lockcd.image.tag=4h

**Comment by vadorovsky** [comment]
That's really odd. Do you have any clue why is this happening? Is that because the configuration from the config map is not read properly?

**Comment by mjura** [comment]
First problem is that previously registered container eBPF maps are lost:

```
          lockcd-19142   [002] d...1 75225.407785: bpf_trace_printk: adding process: success

           <...>-19191   [001] d...1 75225.407923: bpf_trace_printk: error: get_policy_level: could not found a container for a registered process
```
