### ISSUE TITLE
OCI hook which checks if enclave is running

### ISSUE THREAD

**Issue by vadorovsky** [rancher-sandbox/lockc#5]
Containers are secured only when the BPF programs are loaded and pinned. Otherwise, there is no protection.

To prevent users from running not secured containers, let's try to create an OCI hook which will prevent runc (or any other OCI-compatible runtime) from running when enclave BPF programs are not up.

OCI hook `pre-start` ensures that the hook is executed before every run of every container.

Info about OCI hooks:

`man oci-hooks` or https://manpath.be/f30/5/oci-hooks

Example of an OCI hook:

https://github.com/projectatomic/oci-systemd-hook

**Comment by mrostecki** [comment]
I'm getting convinced that the OCI hook will be needed also for #3

**Comment by vadorovsky** [comment]
not needed anymore
